#!/data/data/com.termux/files/usr/bin/bash
read -p "Project path: " P
read -p "Plugin name: " N
read -p "Main class (full package): " M
read -p "API version [1.21]: " A; A="${A:-1.21}"
read -p "Author: " U
mkdir -p "$P/src/main/resources"
cat > "$P/src/main/resources/plugin.yml" <<EOF
name: $N
version: 1.0.0
main: $M
api-version: '$A'
author: $U
description: Generated by LiTool MC
EOF
echo "plugin.yml generated."
